openapi: 3.0.0
info:
  title: Prime Number API
  version: 1.0.0
  description: API to check if a number is prime
servers:
  - url: http://localhost:3000
paths:
  /is_prime:
    get:
      summary: Checks if a number is prime
      parameters:
        - name: number
          in: query
          required: true
          schema:
            type: integer
          description: The number to check for prime
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  number:
                    type: integer
                  is_prime:
                    type: boolean
              example:
                number: 19
                is_prime: true
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Invalid input. Please provide an integer."
